title:            기술블로그
description:      배움의 한계를 뛰어넘는 <br> 끝없는 호기심 <br> <strong> 큐리어슬리입니다. </strong>
description_recruit: 배움의 한계를 뛰어넘는 <br> 끝없는 호기심 <br> <strong> 큐리어슬리와 함께하세요. </strong>

# put your disqus here
disqus_shortname:
reading_time:     false # if true, shows the estimated reading time for a post
words_per_minute: 200
logo:             assets/images/resource/logo.png # logo visible in the topbar
excerpt_separator: <!--more-->
# Your site's domain goes here (eg: //mmistakes.github.io, http://mademistakes.com, etc)
# When testing locally leave blank or use http://localhost:4000
recruit_mode: true
recruit_url: https://www.wanted.co.kr/search?query=%EC%97%90%EC%96%B4%ED%81%B4%EB%9E%98%EC%8A%A4
url: https://raeminkang.github.io
# url: https://localhost:4001
adImage: adImage.png
adUrl: https://www.wanted.co.kr/search?query=%ED%81%90%EB%A6%AC%EC%96%B4%EC%8A%AC%EB%A6%AC
# draw your top menu here
# each item must have a title and a url.
#   To list post categories. use type: 'categories'
#   To create sub categories. add a submenu item
# See the example
image: /images/background.jpg
resource_dir: assets/images/resource
menu:
  - title: 'Categories'
    url: '/category'
    type: 'categories'
  
# Owner/author information
# 기본적으로 posts에 들어있는 게시글은 자동으로 선택된다.
airklass_search:
  include: # 포함할 url을 선택한다.
    pages: false # posts 폴더 이외에 다른 문서 선택 여부 (true일 경우 모든 url이 포함된다.)
    collections: []
  exclude: # 제외시킬 url을 선택한다.
    files: [search.html, index.html, category.html]
    categories: []
    tags: []

# Twitter account associated with the site if different from owner/author twitter account.
# Used in Twitter cards.
# twitter:

# Social networking links used in author block underneath posts. Update and remove as you like.
social:
  - title: "github"
    url: "https://github.com/aron-bordin"
  - title: "linkedin"
    url: "https://br.linkedin.com/in/aronbordin"
  - title: "youtube"
    url: "https://www.youtube.com/channel/UCfnSek-9HPWOx5e2pH7VFgg"

collections:
  authors:
    output: true
    permalink: /authors/:path/
  category:
    output: true
    permalink: /category/:path/
  tags:
    output: true
    permalink: /tags/:path/

defaults:
  - scope:
      path: ''
      type: authors
    values:
      layout: author
  - scope:
      path: ''
      type: category
    values:
      layout: category
  - scope:
      path: ''
      type: tags
    values:
      layout: tag
# KMEMO collection dir name must start "_"
# Background image to be tiled on all pages
background:

# Analytics and webmaster tools stuff goes here
google_analytics:
google_verify:
# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone:    America/New_York
locale:      ko-KR
future:      true
highlighter: rouge
markdown:    kramdown
sass:
  sass_dir: _sass
  style: compressed

# https://github.com/mojombo/jekyll/wiki/Permalinks
# permalink:   /:categories/:title/

# Amount of post to show on home page
paginate: 5

# if true, shows the floatting share buttons
# float_share: true

# Octopress
# Default extensions
post_ext: md
page_ext: md
# Found in _templates/
post_layout: post
page_layout: page
# Format titles with titlecase?
titlecase: false

include: [".htaccess"]
exclude: ["demo/*", "lib", "config.rb", "Capfile", "config", "Gemfile", "Gemfile.lock", "README.md", "LICENSE", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules"]
# plugins: [jekyll-paginate,jekyll-admin,jekyll/tagging]
plugins: [jekyll-paginate, jekyll-sitemap, jekyll-seo-tag, jekyll-feed]
theme: neo-hpstr-jekyll-theme

port: 4001
# tag_page_layout: tag
# tag_page_dir: tags
